# Generated by Django 3.2 on 2021-05-19 21:58

from django.db import migrations, models
import django.db.models.deletion
import submissions.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Central', 'Central Uganda'), ('Southern', 'Southern Uganda'), ('Eastern', 'Eastern Uganda'), ('Northern', 'Northern Uganda'), ('Western', 'Western Uganda')], max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('constituency', models.CharField(max_length=200)),
                ('submission', models.CharField(max_length=60, validators=[submissions.validators.validate_submission])),
                ('submission_category', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Education', 'Education'), ('Health', 'Health'), ('Industry', 'Industry'), ('Security', 'Security'), ('Technology', 'Technology'), ('Tourism', 'Tourism'), ('Others', 'Others')], max_length=200)),
                ('description', models.TextField(max_length=500, validators=[submissions.validators.validate_description])),
                ('submission_status', models.CharField(blank=True, choices=[('solved', 'Solved'), ('inprogress', 'In Progress'), ('pending', 'Pending')], default='pending', max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
